name: Scott Robertson
description: "Scott Robertson, Developer"
url: https://scottrobertson.me
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/:num"
baseurl:
